### ISSUE TITLE
plainText로 일정 등록 시 422 이벤트 데이터 포착 실패 케이스 처리

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#29]
'대충 때되면 도망가기', '무야호' 이런 문장을 plainText 입력으로 보내면 

백엔드에서 '이벤트 데이터 포착 실패' 422 응답 코드를 보낸다.

현재 폼에서 아무 반응도 없으므로 사용자가 알 수 있도록 처리한다.

```
I/flutter (27256): plainText data: {"inputType":1,"originText":"422 케이스","promptId":1}
I/flutter (27256): just e: DioError [DioErrorType.response]: Http status error [422]
I/flutter (27256): Source stack:
I/flutter (27256): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (27256): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (27256): #2      DioMixin.post (package:dio/src/dio_mixin.dart:97:12)
I/flutter (27256): #3      _PlainTextInputState.build.<anonymous closure> (package:mobile_client/widget/plain_text_input.dart:82:46)
I/flutter (27256): <asynchronous suspension>
```

**Comment by call-me-bammer** [comment]
#23 처럼 등록 폼이 나타나지도 않기 때문에 추가로 고려할 사항이 없었습니다.

응답코드 422인 경우, plainText 입력 폼이 내려가며 아래와 같이 SnackBar가 호출되며
그 외 에러의 경우 `catch (e)`로 빼서 유사하게 처리합니다.

![Image](https://github.com/user-attachments/assets/3ab17ed7-1f53-4723-b9ed-be1e8e883253)
