### ISSUE TITLE
일정 정렬 이슈 및 추가 시 표시 에러 발생

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#40]
feature/caledar-ui 브랜치의 가장 최근 커밋 [dfa9d36](https://github.com/SWM-15th-Dnight/flutter-client/commit/dfa9d36293a8294a548863b2bc98686a686925c2)에서 일정 정렬 관련 에러가 있어서 

main_calendar.dart의 해당 부분 주석 처리하고 일단 진행합니다.

```
if (a["summary"] < b["summary"]) return -1;
if (a["summary"] > b["summary"]) return 1;
```

기존 테스트 계정에서 일정을 읽고 이벤트 등록하는 데에 문제가 있는 것 같은데,
저도 코드 다시 쭉 보면서 해결 방법 찾아보겠습니다.

그리고 일정 수동으로 추가 시 바로 월간 뷰에서 제대로 반영되지 않고 다음과 같이 나옵니다. 리프레쉬하면 정상적으로 나와요.

![Image](https://github.com/user-attachments/assets/29f9c6cc-4d29-4b07-826a-6ebc57bdc330)

아래는 에러 내용입니다.

```
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building MainCalendar(dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#86bb3]], state: _MainCalendarState#ecd4a):
Class 'String' has no instance method '<'.
Receiver: "강남"
Tried calling: <("강남")

The relevant error-causing widget was: 
  MainCalendar MainCalendar:file:///Users/bammer/Desktop/git/flutter-client/lib/common/view/splash_screen.dart:33:35
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _MainCalendarState.build.<anonymous closure> (package:mobile_client/screens/calendar/main_calendar.dart:422:30)
#2      Sort._dualPivotQuicksort (dart:_internal/sort.dart:246:36)
#3      Sort._doSort (dart:_internal/sort.dart:60:7)
#4      Sort.sort (dart:_internal/sort.dart:33:5)
#5      ListBase.sort (dart:collection/list.dart:321:10)
#6      _MainCalendarState.build (package:mobile_client/screens/calendar/main_calendar.dart:409:18)
#7      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:27)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:15)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#11     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#38     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#45     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#49     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#53     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#62     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#66     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#72     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#76     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#91     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#92     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#93     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#94     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#95     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#96     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1035:9)
#97     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#101    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
Reloaded 1 of 2023 libraries in 275ms (compile: 31 ms, reload: 110 ms, reassemble: 107 ms).
D/EGL_emulation(11217): app_time_stats: avg=51006.74ms min=51006.74ms max=51006.74ms count=1
```

**Comment by koderpark** [comment]
일정 정렬 관련 부분은 eventId나 priority 값으로 정렬해주면 괜찮을거 같아요
priority로 설정해두겠음
