### ISSUE TITLE
radix-16 관련 에러 로그 표시

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#46]
radix-16 관련 에러 로그가 `feature/publish` 브랜치, `91fccea` 커밋에서 아래와 같이 표시되고 있습니다.
현재 앱 동작에는 별 다른 문제가 없어보이는데 에러 로그 확인 되셨으면 이슈 공유바랍니다.

```
E/flutter ( 4939): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid radix-16 number (at character 2)
E/flutter ( 4939): ffstring
E/flutter ( 4939):  ^
E/flutter ( 4939): 
E/flutter ( 4939): #0      int._handleFormatError (dart:core-patch/integers_patch.dart:127:5)
E/flutter ( 4939): #1      int._parseRadix (dart:core-patch/integers_patch.dart:171:16)
E/flutter ( 4939): #2      int._parse (dart:core-patch/integers_patch.dart:99:12)
E/flutter ( 4939): #3      int.parse (dart:core-patch/integers_patch.dart:61:12)
E/flutter ( 4939): #4      hexToColor (package:mobile_client/entities/color_map.dart:56:20)
E/flutter ( 4939): #5      ColorMap.update (package:mobile_client/entities/color_map.dart:46:36)
E/flutter ( 4939): <asynchronous suspension>
E/flutter ( 4939): 
```

그리고 해당 날짜의 일정 개수에 따라서 점 표시가 (최대 4개) 있는데,
현재 TableCalendar Marker 활용해서 작업 중인 것으로 감안하고 다른 작업 하고 있겠습니다.

![Image](https://github.com/user-attachments/assets/5de56d4e-d68f-4b23-8271-74cdc0a806fa)

**Comment by koderpark** [comment]
점은 의도된 것이 맞읍니다.
버그는 해결 시도해보겠음

**Comment by koderpark** [comment]
백엔드단에서 colorSetId 4 인 경우에 hexcode를 "string"으로 내려주고 있는게 원인인걸 확인했어요.
클라단에서 colorSetId가 4인 경우에 그냥 건너뛰면 되니까 try-catch문 걸어둠.

장기적으로는 colorSetId 4번에 적재된 값을 백엔드에서 바꿔주는 변경이 필요할거같아요.
